[project]
name = "PentaNAS"
version = "0.1.0"
description = "Dedicated to secure, efficient, and private network storage; building and crafting your ideal NAS."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pip>=25.1.1",
    "robyn>=0.71.3",
]
