logger:
  level: "debug"          # 日志级别: debug, info, warn, error, dpanic, panic, fatal
  encoding: "console"     # 编码格式: json, console (console支持彩色输出)
  output_paths:           # 输出路径
    - "stdout"
    - "logs/app.log"
  error_output_paths:     # 错误输出路径
    - "stderr"
    - "logs/error.log"
  development: true       # 开发模式
  disable_caller: false   # 是否禁用调用者信息
  disable_stacktrace: false # 是否禁用堆栈跟踪
  sampling:               # 采样配置
    initial: 100
    thereafter: 100
  encoder_config:         # 编码器配置
    time_key: "T"
    level_key: "L"
    name_key: "N"
    caller_key: "C"
    message_key: "M"
    stacktrace_key: "S"
    line_ending: ""
    level_encoder: "color"        # color 启用彩色日志等级
    time_encoder: "iso8601"       # iso8601, millis, nanos, rfc3339
    duration_encoder: "seconds"   # seconds, nanos, ms
    caller_encoder: "short"       # full, short
